// @ts-nocheck
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 获取所有轮次
 */
async getRoutines() : Promise<Result<Routine[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_routines") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 创建轮次
 */
async createRoutine(name: string, desc: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_routine", { name, desc }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除轮次
 */
async deleteRoutine(routineId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_routine", { routineId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 更新轮次
 */
async updateRoutine(routineId: number, name: string, desc: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_routine", { routineId, name, desc }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取轮次下的动作
 */
async getExercises(routineId: number) : Promise<Result<Exercise[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_exercises", { routineId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 添加动作
 */
async addExercise(routineId: number, name: string, sets: number, reps: string, note: string, unit: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_exercise", { routineId, name, sets, reps, note, unit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除动作
 */
async deleteExercise(exerciseId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_exercise", { exerciseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 更新动作
 */
async updateExercise(exerciseId: number, name: string, sets: number, reps: string, note: string, unit: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_exercise", { exerciseId, name, sets, reps, note, unit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 记录一次最大重量
 */
async addRecord(exerciseId: number, weight: number, reps: number | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_record", { exerciseId, weight, reps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除记录
 */
async deleteRecord(recordId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_record", { recordId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 分页获取记录
 */
async getAllRecords(exerciseId: number) : Promise<Result<Record[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_records", { exerciseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 更新记录
 */
async updateRecord(recordId: number, weight: number, reps: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_record", { recordId, weight, reps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取单个动作的统计信息
 */
async getExerciseStats(exerciseId: number) : Promise<Result<ExerciseStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_exercise_stats", { exerciseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDbBytes() : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_db_bytes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importDbFromBytes(bytes: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_db_from_bytes", { bytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartApp() : Promise<void> {
    await TAURI_INVOKE("restart_app");
},
/**
 * 获取某个动作的常用次数列表
 */
async getCommonReps(exerciseId: number) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_common_reps", { exerciseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Exercise = { id: number; routineId: number; 
/**
 * 动作名称
 */
name: string; 
/**
 * 计划做几组
 */
targetSets: number; 
/**
 * 计划做几个 (用String是为了支持 "8-12" 这种写法)
 */
targetReps: string; 
/**
 * 详细描述 (离心要慢...)
 */
note: string | null; 
/**
 * 记录时的单位 'kg', 'lb', 'plate' (多少片)
 */
unit: string }
export type ExerciseStats = { exerciseId: number; totalRecords: number; maxWeight: number | null; lastDate: number }
export type Record = { id: number; exerciseId: number; 
/**
 * 记录时间
 */
createdAt: number; 
/**
 * 重量 (数值，配合Exercise里的unit使用)
 */
weight: number; 
/**
 * 实际做了几个
 */
reps: number | null }
export type Routine = { id: number; 
/**
 * 轮次名称
 */
name: string; 
/**
 * 可选描述
 */
description: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
